In [2]:
import numpy as np

# NumPy - Numerical Python

- 파이썬 산술 계산을 위한 패키지
- NumPy 배열 객체는 데이터 교환을 위한 공통 언어처럼 사용 -> R 등 다른 언어에서 호환이 쉬움
- ** 파이썬의 연속된 자료형보다 더 적은 메모리 사용 **
    리스트 : 메모리 주소에 객체의 위치 저장
    넘파이 : 연속된 메모리 주소에 객체의 위치 저장
        -> (같은 크기의 같은 자료형만을 담을 수 있기 때문에 가능) 배열의 첫 번째 주소만 알면 됨
- 다양한 계산 수행 적합

In [13]:
matrix_1 = [[1,2],[3,4]]
matrix_2 = [[5,6],[7,8]]

matrix_result = np.array(matrix_1)+np.array(matrix_2)
print(matrix_result)

np.shape(matrix_result)

[[ 6  8]
 [10 12]]


(2, 2)

In [42]:
# ndarray

array0d = np.array(1)
array1d = np.array([1,2])
array2d = np.array([[1,2,3,4,5],[4,5,6,7,8],[7,8,9,10,11]])
array3d = np.array([[[1,1,1,1],[2,2,2,2],[3,3,3,3]],[[1,1,1,1],[2,2,2,2],[3,3,3,3]]])
array3d_2 = np.array([[[0]*4 for _ in range (3)] for _ in range (2)])
print(array3d_2.shape)

print('배열의 구조 :',array3d.shape)
print('배열의 차원(dimensions) :', array3d.ndim)
print('전체 원소의 개수 :', array3d.size)

(2, 3, 4)
배열의 구조 : (2, 3, 4)
배열의 차원(dimensions) : 3
전체 원소의 개수 : 24


In [46]:
# 자료형

x = np.array([1,2,3],dtype='f')
print(f'''{x.dtype}
{x[0] + x[1]}''')
print()
x = np.array([1,2,3],dtype='U')
print(f'''{x.dtype}
{x[0] + x[1]}''')

float32
3.0

<U1
12


In [52]:
# 무한대

print(f'''np.inf(무한대) = {np.inf}
np.nan(정의할 수 없는 숫자) = {np.nan}
-np.inf(-무한대) = {-np.inf}''')

np.inf(무한대) = inf
np.nan(정의할 수 없는 숫자) = nan
-np.inf(-무한대) = -inf


In [104]:
# 벡터화 연산

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2*a+b)
print(a == 2)
print(b>10)
print((a==2)&(b>10))

#벡터화 연산 연습문제
c = np.array([
    [1,2,3],
    [4,5,6]
    ])
d = np.array([
    [7,8,9],
    [10,11,12]
    ])
print(c+d)

#벡터화 연산 연습문제2
ndarray = np.array([_ for _ in range(1,10)])
print(ndarray*3)

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]
[[ 8 10 12]
 [14 16 18]]
[ 3  6  9 12 15 18 21 24 27]


In [118]:
# 다차원 배열 생성
x = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
])
# 배열 출력
print("배열 x:")
print(x)
# 배열의 shape 확인
print("\nx의 shape:", x.shape)
print(x)


print(x[0,1])
print(x[0,2,1])
print(x[1,0,0::2])
print(x[0:,2])

print(x[0:2, 0::2])

배열 x:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]

x의 shape: (2, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]
  [70 80 90]]]
[4 5 6]
8
[10 30]
[[ 7  8  9]
 [70 80 90]]

[[[ 1  2  3]
  [ 7  8  9]]

 [[10 20 30]
  [70 80 90]]]


In [126]:
# 슬라이싱 연습문제
m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

print(m.shape)

print(m[1, 2])
print(m[2, 4])
print(m[1,1:3])
print(m[1:3, 2])
print(m[0:2, 3:5])

(3, 5)
7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [134]:
#zeros, ones, zeros/ones_like

c = np.zeros((5,2), dtype='f')
print(c)

d = np.ones((2,3,4), dtype='i8')
print(d)

e = np.zeros_like(d, dtype='f')         #np.zeros_like(따라할 배열, 타입)
print(e)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [31]:
# 배열 생성, 슬라이싱 연습문제

a = np.ones((9,9), dtype='f')
a[-1:0:-1, -1:0:-1] = 0

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [148]:
#배열, 슬라이싱 연습문제 체커보드
a = np.ones((8,8), dtype='f')
for x in range(8) :
    if x%2!=0 :
        a[x,0::2] = 0
    else :
        a[x,1::2] = 0

print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [150]:
# np.empty((shape))

#배열의 크기가 커지면 초기화 시간이 증가 -> 특정 값으로 초기화하지 않은 명령어, 원래 메모리에 들어있는 쓰레기값으로 만들어줌

g = np.empty((4,3))
g

array([[4.67296746e-307, 1.69121096e-306, 9.45698831e-308],
       [1.89146896e-307, 7.56571288e-307, 3.11525958e-307],
       [1.24610723e-306, 1.29061142e-306, 1.39077302e-307],
       [9.34562257e-307, 1.37962388e-306, 1.78019625e-306]])

In [152]:
# np.arange(start, end, step)수열을 이용한 배열 생성

np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [158]:
# np.random.~ 랜덤 배열 생성

#np.random.random((shape)) : 0~1 사이의 균일 분포를 따르는 난수 생성
print('random :',np.random.random((3,2)))

#np.random.rand(shape) : 0~1의 균일 분포에서 난수 생성
print('rand :',np.random.rand(3,3))

#np.random.randint(start, end, size) : start~(end-1)의 균일 분포에서 난수 생성
print('randint :', np.random.randint(1, 10, (2,3)))

#np.random.randn(shape) :
print('randn :',np.random.randn(3,3))


#random은 shape를 튜플로 받기 때문에 shape가 튜플이라면 random,
#튜플 형태의 shape를 rand에서 쓰려면 np.random.rand(*shape)

shape = (2, 3)

print(np.random.random(shape))
print(np.random.rand(*shape))

random : [[0.16870457 0.29913335]
 [0.85366766 0.53228934]
 [0.68994396 0.15850845]]
rand : [[0.26584696 0.74984502 0.56166733]
 [0.47171975 0.62056071 0.69521352]
 [0.64120441 0.70357132 0.36928407]]
randint : [[9 3 4]
 [7 7 4]]
randn : [[-0.94768658  0.46685343 -0.93050024]
 [ 0.14948518 -0.06461636 -1.45556837]
 [ 0.98430835  0.88541616 -1.22380975]]
[[0.61809388 0.38031766 0.66195923]
 [0.25048074 0.91009261 0.339339  ]]
[[0.55450665 0.52454012 0.62463014]
 [0.61740157 0.70293349 0.15136002]]


In [161]:
# np.linspace/np.logspace(start, stop, num)
print("np.linspace(0,100,5) :",np.linspace(0,100,5))
print("np.logspace(0,100,5) :",np.logspace(0,100,5))

np.linspace(0,100,5) : [  0.  25.  50.  75. 100.]
np.logspace(0,100,5) : [1.e+000 1.e+025 1.e+050 1.e+075 1.e+100]


In [169]:
#linspace() 연습문제\

np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [144]:
ndarray = np.ones((3,3,3), dtype='U10')
ndarray[0:3] = ''
ndarray

array([[['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']],

       [['', '', ''],
        ['', '', ''],
        ['', '', '']]], dtype='<U10')

In [5]:
# 배열의 크기 변경 np.reshape(shape)

a = np.arange(12)
b = a.reshape(3,4)
print('a :', a)
print('b :', b)

c = a.reshape(2,2,3)
print('c :', c)

d = a.reshape(2,-1,3)
print('d :',d)

a : [ 0  1  2  3  4  5  6  7  8  9 10 11]
b : [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
c : [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
d : [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [10]:
#array.reshape 연습문제

ndarray = np.arange(2, 41, 2)
a = ndarray.reshape(2,2,5)      #reshape는 값을 새로 저장해줘야 함
print(ndarray)
print(a)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[[[ 2  4  6  8 10]
  [12 14 16 18 20]]

 [[22 24 26 28 30]
  [32 34 36 38 40]]]


In [ ]:
# 차원 축소 a.flatten(), a.ravel()
#ravel은 원본이 바뀜

In [30]:
# 전치 행렬 a.T -> 행과 열을 바꿈
a = np.arange(6).reshape(2,3)
print(a)
print(a.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]


In [34]:
#hstack, vstack 수평, 수직 연결

a = np.arange(1,7).reshape(2,3)
b = np.arange(10,61,10).reshape(2,3)
print('hstack(수평 연결) :\n', np.hstack([a,b]))

hstack(수평 연결) :
 [[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [42]:
#수평, 수직 연결 연습

a = np.zeros((3,3), dtype='f')
b = np.ones((3,2), dtype='f')
c = np.arange(10,151,10).reshape(3,5)
d = np.vstack([np.hstack([a, b]),c])
print(np.vstack([d,d]))


[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


# 브로드캐스팅
모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시킴
-> 크기가 작은 배열이 크기가 큰 배열로 변환

항상 가능한 것은 아님
- 조건
    - 차원 중 하나가 1인 경우
    - 차원의 축의 크기가 동일한 경우

# 넘파이 메소드

In [48]:
# argmin/argmax (해당 배열의 최소, 최대값의 인덱스 반환)
# 다차원 배열의 경우 1차원 배열로 축소시켜 이넥스 반환

arr = np.reshape(np.random.randint(100, size = (12)),(2,3,-1))
display(arr)

print(f'''max index : {np.argmax(arr)}
max value : {arr.flatten()[np.argmax(arr)]}
min index : {np.argmin(arr)}
min value : {arr.flatten()[np.argmin(arr)]}''')

array([[[70, 21],
        [49, 57],
        [ 3, 68]],

       [[24, 43],
        [76, 26],
        [52, 80]]])

max index : 11
max value : 80
min index : 4
min value : 3


In [57]:
#argmin의 축 설정
np.random.seed(1)
arr = np.reshape(np.random.randint(100, size=24), (2, 3, 2, -1))
print(arr.shape)
print(arr)
print('axis=0\n', np.argmin(arr, axis=0))
print('axis=1\n', np.argmax(arr, axis=1))
print('axis=2\n', np.argmax(arr, axis=2))
print('--'*10)
print(np.sort(arr,axis=2))

(2, 3, 2, 2)
[[[[37 12]
   [72  9]]

  [[75  5]
   [79 64]]

  [[16  1]
   [76 71]]]


 [[[ 6 25]
   [50 20]]

  [[18 84]
   [11 28]]

  [[29 14]
   [50 68]]]]
axis=0
 [[[1 0]
  [1 0]]

 [[1 0]
  [1 1]]

 [[0 0]
  [1 1]]]
axis=1
 [[[1 0]
  [1 2]]

 [[2 1]
  [0 2]]]
axis=2
 [[[1 0]
  [1 1]
  [1 1]]

 [[1 0]
  [0 0]
  [1 1]]]
--------------------
[[[[37  9]
   [72 12]]

  [[75  5]
   [79 64]]

  [[16  1]
   [76 71]]]


 [[[ 6 20]
   [50 25]]

  [[11 28]
   [18 84]]

  [[29 14]
   [50 68]]]]


In [60]:
x = np.arange(12)
print(f'x.shape : {x.shape}, x.ndim : {x.ndim}')
print(x)
x = x[:, np.newaxis]
print(f'x.shape : {x.shape}, x.ndim : {x.ndim}')
print(x)
x = x[np.newaxis, :]
print(f'x.shape : {x.shape}, x.ndim : {x.ndim}')
print(x)

x.shape : (12,), x.ndim : 1
[ 0  1  2  3  4  5  6  7  8  9 10 11]
x.shape : (12, 1), x.ndim : 2
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
x.shape : (1, 12, 1), x.ndim : 3
[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]]
